### ISSUE TITLE
Fei4Emu::initializePixelModelsFromFile does not check for existence of file

### ISSUE THREAD

**Issue by weatherhead99** [Yarr/Yarr#10]
when running the example commands for the scanConsole in the emulator, using a CMake build, the command doesn't work because the directory structure is different. This is trivial to debug, of course, but then a less obvious error is found  (see output below) - since the paths in the supplied .json files are relative, the file configs/emulator/emu_fe0.json isn't found in this case. This error arises from Fei4Emu::initializePixelModelsFromFile (found using backtrace). However, this function uses a std::ifstream then doesn't check if it's good. This is a minor error, but spurious, because in fact this isn't a json parse fail at all, it's a failure to find the file at all.

Very happy to submit a patch (e.g. throwing an exception here), but can't easily figure out whether you have an aversion to throwing exceptions in this code, or what exception to throw.

Thanks for all the hard work!

```
./bin/scanConsole  -r ../configs/controller/emuCfg.json -c ../configs/connectivity/example_fei4b_setup.json -s ../configs/scans/fei4/std_digitalscan.json -p
#####################################
# Welcome to the YARR Scan Console! #
#####################################
> Parsing command line parameters ...
 Scan Type/Config: ../configs/scans/fei4/std_digitalscan.json
 Connectivity: 
    ../configs/connectivity/example_fei4b_setup.json
 Target ToT: -1
 Target Charge: -1
 Output Plots: 1
 Output Directory: ./data/000010_std_digitalscan/

Timestamp: 2018-08-03_03:52:45
Run Number: 10
#################
# Init Hardware #
#################
-> Opening controller config: ../configs/controller/emuCfg.json
-> Found config for controller emu
-> Starting Emulator
configs/emulator/emu_fe0.json
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)
```

**Comment by weiminsong** [comment]
Hi, 
Do you have any problem to it in the main folder?
I mean ./build/bin XXXXX

Best wishes, 
Weimin

**Comment by weatherhead99** [comment]
Yes, it works fine in that case. It's just that this error message is still
spurious in any case
