### ISSUE TITLE
On branch 'Master', in src/libFei4/Fei4PixelCfg.cpp

### ISSUE THREAD

**Issue by phyz777** [Yarr/Yarr#4]
void Fei4PixelCfg::fromFileJson(json &j) {
    // Layout is one array per column
    for (unsigned row=1; row<=n_Row; row++) {
        for (unsigned col=1; col<=n_Col; col++) {
            setEn(col, row, j["FE-I4B"]["PixelConfig"][row-1]["Enable"][col-1]);
            setHitbus(col, row, j["FE-I4B"]["PixelConfig"][row-1]["Enable"][col-1]);
            setTDAC(col, row, j["FE-I4B"]["PixelConfig"][row-1]["Enable"][col-1]);
            setFDAC(col, row, j["FE-I4B"]["PixelConfig"][row-1]["Enable"][col-1]);
        }
    }

}

Es wird immer das "Enable" von dem Objekt abgegriffen! 

//edit: Lösungsvorschlag liegt im branch 'devel_jsonCfgFix' zur Revision

**Comment by phyz777** [comment]
I think all is merged, so it should be okay to close this issue?

**Comment by baramsel** [comment]
Indeed
